# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['main.py'],
             pathex=['C:\\Users\\Mahdi\\Github\\jottr\\src\\jottr'],
             binaries=[('C:\\Python\\Python313\\Lib\\site-packages\\enchant\\data\\mingw64\\bin\\libenchant-2.dll', 'enchant'),
                       ('C:\\Python\\Python313\\Lib\\site-packages\\enchant\\data\\mingw64\\bin\\libglib-2.0-0.dll', '.'),
                       ('C:\\Python\\Python313\\Lib\\site-packages\\enchant\\data\\mingw64\\bin\\libhunspell-1.6-0.dll', '.')],
             datas=[('editor_tab.py', '.'),
                    ('snippet_manager.py', '.'),
                    ('rss_tab.py', '.'),
                    ('theme_manager.py', '.'),
                    ('settings_manager.py', '.'),
                    ('settings_dialog.py', '.'),
                    ('snippet_editor_dialog.py', '.'),
                    ('rss_reader.py', '.'),
                    ('icons', 'icons'),
                    ('help', 'help'),
                    ('C:\\Python\\Python313\\Lib\\site-packages\\enchant', 'enchant')],
             hiddenimports=['ctypes', 'ctypes.util', 'pyenchant'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
          cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='jottr',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False,
          icon='app.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='jottr')