name: Build Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-stdeb python3-all dh-python
          
      - name: Build package
        run: |
          python3 setup.py --command-packages=stdeb.command bdist_deb
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: deb_dist/*.deb
