name: Build DEB Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pyqt5 python3-pyqt5.qtwebengine
          python -m pip install --upgrade pip
          pip install build PyQt5 PyQtWebEngine

      - name: Create DEB package structure
        run: |
          mkdir -p .debpkg/usr/lib/jottr
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/share/applications
          mkdir -p .debpkg/usr/share/icons/hicolor/128x128/apps
          mkdir -p .debpkg/usr/share/doc/jottr
          mkdir -p .debpkg/usr/share/man/man1
          mkdir -p .debpkg/DEBIAN
          
          # Copy application files
          cp main.py .debpkg/usr/lib/jottr/
          cp -r icons .debpkg/usr/lib/jottr/
          
          # Create launcher script
          echo '#!/bin/sh
          exec python3 /usr/lib/jottr/main.py "$@"' > .debpkg/usr/bin/jottr
          chmod +x .debpkg/usr/bin/jottr
          
          # Copy icons
          cp icons/jottr.png .debpkg/usr/share/icons/hicolor/128x128/apps/
          
          # Create changelog
          echo "jottr (${VERSION:-0.0.0}) unstable; urgency=medium
          
            * Initial release.
          
           -- mFat <newmfat@gmail.com>  $(date -R)" > .debpkg/usr/share/doc/jottr/changelog
          gzip -9 -n .debpkg/usr/share/doc/jottr/changelog
          
          # Create copyright file
          echo "Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
          Source: https://github.com/mfat/jottr
          
          Files: *
          Copyright: 2024 mFat <newmfat@gmail.com>
          License: GPL-3.0+" > .debpkg/usr/share/doc/jottr/copyright
          
          # Create man page
          echo ".TH JOTTR 1 \"$(date +"%B %Y")\" \"jottr ${VERSION:-0.0.0}\"
          .SH NAME
          jottr \\- text editor for writers and journalists
          .SH SYNOPSIS
          .B jottr
          .SH DESCRIPTION
          Text editor designed for writers and journalists with features for content creation.
          .SH AUTHOR
          Written by mFat <newmfat@gmail.com>
          .SH BUGS
          Report bugs to: https://github.com/mfat/jottr/issues" > .debpkg/usr/share/man/man1/jottr.1
          gzip -9 -n .debpkg/usr/share/man/man1/jottr.1
          
          # Create postinst script
          cat > .debpkg/DEBIAN/postinst << 'EOF'
          #!/bin/sh
          set -e

          pip3 install --break-system-packages pyspellchecker

          #DEBHELPER#
          exit 0
          EOF
          chmod 755 .debpkg/DEBIAN/postinst

      - name: Build DEB package
        uses: jiro4989/build-deb-action@v4
        with:
          package: jottr
          package_root: .debpkg
          maintainer: 'mFat <newmfat@gmail.com>'
          version: ${{ github.ref_type == 'tag' && github.ref_name || '0.0.0' }}
          arch: 'all'
          homepage: 'https://github.com/mfat/jottr'
          section: 'editors'
          desc: |
            Modern text editor for writers and journalists
            .
            Jottr is a feature-rich text editor designed specifically
            for writers and journalists, with features like smart
            completion, snippets, and integrated web browsing.
          compress_type: 'xz'
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            *.deb

  create-release:
    needs: [build-deb]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 