name: Build Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper devscripts python3-setuptools python3-all dh-python
          python -m pip install --upgrade pip
          pip install build

      - name: Build source distribution
        run: |
          python -m build --sdist
          
      - name: Build DEB package
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          else
            VERSION="0.0.0"
          fi
          cd packaging/debian
          ./build.sh "$VERSION"
          cd ../..

      - name: Prepare RPM sources
        run: |
          VERSION="0.0.0"
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          fi
          mkdir -p /github/home/rpmbuild/{SPECS,SOURCES}
          cp dist/jottr-${VERSION}.tar.gz /github/home/rpmbuild/SOURCES/python3-jottr-${VERSION}.tar.gz
          cp packaging/rpm/jottr.spec /github/home/rpmbuild/SPECS/

      - name: Build RPM package
        id: rpm
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: "jottr.spec"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            packaging/debian/*.deb
            ${{ steps.rpm.outputs.rpm_dir_path }}/*.rpm

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pyinstaller
          
      - name: Build macOS binary
        run: |
          pyinstaller --name jottr \
                     --onefile \
                     --windowed \
                     main.py
          
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: jottr-darwin-${{ matrix.arch }}
          path: dist/jottr

  create-release:
    needs: [build-macos, build-packages]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages/*
            jottr-darwin-x86_64/*
            jottr-darwin-arm64/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos-universal:
    needs: [create-release]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download AMD64 binary
        uses: actions/download-artifact@v4
        with:
          name: jottr-darwin-x86_64
          path: darwin-amd64
          
      - name: Download ARM64 binary
        uses: actions/download-artifact@v4
        with:
          name: jottr-darwin-arm64
          path: darwin-arm64
          
      - name: Create Universal Binary
        uses: manojkarthick/macos-universal-binary-action@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: ${{ github.repository_owner }}
          repository: ${{ github.event.repository.name }}
          tag: ${{ github.ref_name }}
          amd64: "darwin-amd64/jottr"
          arm64: "darwin-arm64/jottr"
          compressed: true
          overwrite: true
          universal-identifier: "darwin-universal" 