name: Build Debian Package

on:
  tags: [ 'v*' ]
  workflow_dispatch:

# Add these permission settings
permissions:
  contents: write
  packages: write

jobs:
  build-deb:
    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            devscripts \
            debhelper \
            dh-python \
            python3-all \
            python3-setuptools \
            python3-pyqt5 \
            python3-pyqt5.qtwebengine \
            python3-feedparser \
            python3-enchant \
            python3-pyqt5.qtsvg \
            python3-pip \
            unzip \
            git \
            build-essential

      # Add step to download pyspellchecker
      - name: Download pyspellchecker
        run: |
          mkdir -p src/jottr/vendor/
          pip3 download pyspellchecker --no-deps -d src/jottr/vendor/
          cd src/jottr/vendor/
          unzip pyspellchecker*.whl
          rm -rf pyspellchecker*.whl *.dist-info/

      - name: Create debian directory link
        run: |
          rm -rf debian
          ln -s packaging/debian debian

      - name: Update changelog date
        run: |
          sed -i "s/\$(LC_ALL=C date -R)/$(LC_ALL=C date -R)/" debian/changelog

      - name: Build package
        run: |
          dpkg-buildpackage -us -uc -b -d
          mkdir -p artifacts
          mv ../*.deb artifacts/

      - name: List built packages
        run: ls -l artifacts/*.deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: artifacts/*.deb

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.deb
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 