name: Build Debian Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create GitHub Release'
        required: true
        default: false
        type: boolean
      release_type:
        description: 'Release Type (if creating release)'
        required: false
        default: 'beta'
        type: choice
        options:
          - beta
          - stable
      version:
        description: 'Version (if creating release)'
        required: false
        type: string

jobs:
  build-deb:
    runs-on: ubuntu-latest
    container: debian:trixie

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y devscripts debhelper python3-all python3-setuptools \
                           python3-pyqt5 python3-pyqt5.qtwebengine python3-feedparser \
                           git  # needed for actions/checkout

      - name: Create debian directory link
        run: |
          rm -rf debian
          ln -s packaging/debian debian

      - name: Update changelog date
        run: |
          sed -i "s/\$(LC_ALL=C date -R)/$(LC_ALL=C date -R)/" debian/changelog

      - name: Build package
        run: |
          dpkg-buildpackage -us -uc -b
          mkdir -p artifacts
          mv ../*.deb artifacts/

      - name: List built packages
        run: ls -l artifacts/*.deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: artifacts/*.deb

      - name: Create Release (from tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release (from workflow dispatch)
        if: github.event_name == 'workflow_dispatch' && inputs.create_release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.deb
          tag_name: ${{ inputs.version || format('v{0}', github.run_number) }}
          name: ${{ inputs.release_type == 'stable' && 'Release' || 'Beta Release' }} ${{ inputs.version || format('v{0}', github.run_number) }}
          draft: false
          prerelease: ${{ inputs.release_type == 'beta' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 