name: Build Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build source distribution
        run: |
          python -m build --sdist
          
      - name: Create DEB package structure
        run: |
          mkdir -p .debpkg/usr/lib/jottr
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/share/applications
          mkdir -p .debpkg/usr/share/icons/hicolor/128x128/apps
          mkdir -p .debpkg/usr/share/doc/jottr
          mkdir -p .debpkg/usr/share/man/man1
          
          # Copy application files
          cp -r dist/* .debpkg/usr/lib/jottr/
          cp -r icons .debpkg/usr/lib/jottr/
          
          # Create launcher script
          echo '#!/bin/sh
          exec python3 /usr/lib/jottr/main.py "$@"' > .debpkg/usr/bin/jottr
          chmod +x .debpkg/usr/bin/jottr
          
          # Copy icons (to correct resolution directory)
          cp icons/jottr.png .debpkg/usr/share/icons/hicolor/128x128/apps/
          
          # Create changelog
          echo "jottr (${VERSION:-0.0.0}) unstable; urgency=medium

            * Initial release.

           -- mFat <newmfat@gmail.com>  $(date -R)" > .debpkg/usr/share/doc/jottr/changelog
          gzip -9 -n .debpkg/usr/share/doc/jottr/changelog
          
          # Create copyright file
          echo "Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
          Source: https://github.com/mfat/jottr
          
          Files: *
          Copyright: 2024 mFat <newmfat@gmail.com>
          License: GPL-3.0+" > .debpkg/usr/share/doc/jottr/copyright
          
          # Create man page
          echo ".TH JOTTR 1 \"$(date +"%B %Y")\" \"jottr ${VERSION:-0.0.0}\"
          .SH NAME
          jottr \\- text editor for writers and journalists
          .SH SYNOPSIS
          .B jottr
          .SH DESCRIPTION
          Text editor designed for writers and journalists with features for content creation.
          .SH AUTHOR
          Written by mFat <newmfat@gmail.com>
          .SH BUGS
          Report bugs to: https://github.com/mfat/jottr/issues" > .debpkg/usr/share/man/man1/jottr.1
          gzip -9 -n .debpkg/usr/share/man/man1/jottr.1
          
      - name: Build DEB package
        uses: jiro4989/build-deb-action@v4
        with:
          package: python3-jottr
          package_root: .debpkg
          maintainer: 'mFat <newmfat@gmail.com>'
          version: ${{ github.ref_type == 'tag' && github.ref_name || '0.0.0' }}
          arch: 'all'
          depends: 'python3, python3-pyqt5, python3-pyqt5.qtwebengine, python3-spellchecker'
          homepage: 'https://github.com/mfat/jottr'
          section: 'editors'
          priority: 'optional'
          desc: |
            Modern text editor for writers and journalists
            .
            Jottr is a feature-rich text editor designed specifically
            for writers and journalists, with features like smart
            completion, snippets, and integrated web browsing.
          compress_type: 'xz'
          
      - name: Create RPM package structure
        run: |
          mkdir -p .rpmpkg/usr/bin
          mkdir -p .rpmpkg/usr/lib/jottr
          mkdir -p .rpmpkg/usr/share/applications
          mkdir -p .rpmpkg/usr/share/icons/hicolor/scalable/apps
          
          # Copy application files
          cp -r dist/* .rpmpkg/usr/lib/jottr/
          cp -r icons .rpmpkg/usr/lib/jottr/
          
          # Create launcher script
          echo '#!/bin/sh
          exec python3 /usr/lib/jottr/main.py "$@"' > .rpmpkg/usr/bin/jottr
          chmod +x .rpmpkg/usr/bin/jottr
          
          # Copy desktop file and icons
          cp icons/jottr.png .rpmpkg/usr/share/icons/hicolor/scalable/apps/

      - name: Build RPM package
        uses: jiro4989/build-rpm-action@v2
        with:
          summary: 'A modern text editor designed for writers and journalists'
          package: jottr
          package_root: .rpmpkg
          maintainer: 'mFat <newmfat@gmail.com>'
          version: ${{ github.ref_type == 'tag' && github.ref_name || '0.0.0' }}
          arch: 'x86_64'
          desc: 'A modern text editor designed for writers and journalists.'
          depends: 'python3 python3-qt5 python3-qt5-webengine python3-spellchecker'
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            *.deb
            *.rpm

  create-release:
    needs: [build-packages]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
